//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssigmentWPF
{
    using System;


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1()
        {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryAssigmentWPF.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на AddBook.
        /// </summary>
        internal static string btnAddBook
        {
            get
            {
                return ResourceManager.GetString("btnAddBook", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to Cart.
        /// </summary>
        internal static string btnAddCart
        {
            get
            {
                return ResourceManager.GetString("btnAddCart", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Journal.
        /// </summary>
        internal static string btnAddJournal
        {
            get
            {
                return ResourceManager.GetString("btnAddJournal", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Cart.
        /// </summary>
        internal static string btnCart
        {
            get
            {
                return ResourceManager.GetString("btnCart", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Checkout.
        /// </summary>
        internal static string btnCheckOut
        {
            get
            {
                return ResourceManager.GetString("btnCheckOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Customer to club.
        /// </summary>
        internal static string btnClub
        {
            get
            {
                return ResourceManager.GetString("btnClub", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Club Customers.
        /// </summary>
        internal static string btnClubCostumers
        {
            get
            {
                return ResourceManager.GetString("btnClubCostumers", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Activate Club Discount.
        /// </summary>
        internal static string btnClubDiscount
        {
            get
            {
                return ResourceManager.GetString("btnClubDiscount", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Book.
        /// </summary>
        internal static string btnEditBook
        {
            get
            {
                return ResourceManager.GetString("btnEditBook", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Journal.
        /// </summary>
        internal static string btnEditJournal
        {
            get
            {
                return ResourceManager.GetString("btnEditJournal", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter.
        /// </summary>
        internal static string btnEnter
        {
            get
            {
                return ResourceManager.GetString("btnEnter", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string btnExit
        {
            get
            {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Find Items By Name.
        /// </summary>
        internal static string btnFind
        {
            get
            {
                return ResourceManager.GetString("btnFind", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Return to Main Menu.
        /// </summary>
        internal static string btnMainMenu
        {
            get
            {
                return ResourceManager.GetString("btnMainMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Book Receipts.
        /// </summary>
        internal static string btnManageBooks
        {
            get
            {
                return ResourceManager.GetString("btnManageBooks", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Journal Receipts.
        /// </summary>
        internal static string btnManageJournals
        {
            get
            {
                return ResourceManager.GetString("btnManageJournals", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay.
        /// </summary>
        internal static string btnPay
        {
            get
            {
                return ResourceManager.GetString("btnPay", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage Purchases.
        /// </summary>
        internal static string btnPurcchases
        {
            get
            {
                return ResourceManager.GetString("btnPurcchases", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove Book.
        /// </summary>
        internal static string btnRemoveBook
        {
            get
            {
                return ResourceManager.GetString("btnRemoveBook", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove From Cart.
        /// </summary>
        internal static string btnRemoveCart
        {
            get
            {
                return ResourceManager.GetString("btnRemoveCart", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove Customer From Club.
        /// </summary>
        internal static string btnRemoveCustomer
        {
            get
            {
                return ResourceManager.GetString("btnRemoveCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove Journal.
        /// </summary>
        internal static string btnRemoveJournal
        {
            get
            {
                return ResourceManager.GetString("btnRemoveJournal", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Return.
        /// </summary>
        internal static string btnReturn
        {
            get
            {
                return ResourceManager.GetString("btnReturn", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Sell Book.
        /// </summary>
        internal static string btnSellBook
        {
            get
            {
                return ResourceManager.GetString("btnSellBook", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Sell Items.
        /// </summary>
        internal static string btnSellItems
        {
            get
            {
                return ResourceManager.GetString("btnSellItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Sell Journal.
        /// </summary>
        internal static string btnSellJournal
        {
            get
            {
                return ResourceManager.GetString("btnSellJournal", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Available Books.
        /// </summary>
        internal static string btnShowBooks
        {
            get
            {
                return ResourceManager.GetString("btnShowBooks", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Available Items.
        /// </summary>
        internal static string btnShowItems
        {
            get
            {
                return ResourceManager.GetString("btnShowItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Available Journals.
        /// </summary>
        internal static string btnShowJournals
        {
            get
            {
                return ResourceManager.GetString("btnShowJournals", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to Word.
        /// </summary>
        internal static string btnWord
        {
            get
            {
                return ResourceManager.GetString("btnWord", resourceCulture);
            }
        }
    }
}
